name: Build

on:
  push:
  workflow_dispatch:

jobs:
  bun:
    timeout-minutes: 10
    strategy:
      matrix:
        # No bun on windows
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - if: runner.os == 'macOS'
        run: brew install protobuf
      - run: |
          curl -fsSL https://bun.sh/install | bash
          echo "BUN_INSTALL=$HOME/.bun" >> $GITHUB_ENV
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno run -A --unstable https://deno.land/x/pact/src/downloadFfi.ts --run
      - run: curl -fsSL https://raw.githubusercontent.com/pact-foundation/pact-plugins/main/scripts/install-plugin-cli.sh | bash
      - run: /home/runner/bin/pact-plugin-cli -y install https://github.com/pactflow/pact-protobuf-plugin/releases/latest
        if: runner.os == 'Linux'
      - run: /Users/runner/bin/pact-plugin-cli -y install https://github.com/pactflow/pact-protobuf-plugin/releases/latest
        if: runner.os == 'macOS'
      - run: bun install
      - run: bun run src/http.consumer.test.ts
      - run: bun run src/grpc.consumer.test.ts
  bun_win:
    timeout-minutes: 10
    strategy:
      matrix:
        # No bun on windows
        os: [windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
      - uses: actions/checkout@v3
      - uses: Vampire/setup-wsl@v1
      # - if: runner.os == 'Windows'
      #   run: choco install protobuf
      - run: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="/root/.bun"
          export PATH="/root/.bun/bin:$PATH"
          bun --version
      - run: apt update && apt install -y curl unzip
      - run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          export DENO_INSTALL="/root/.deno"
          export PATH="$DENO_INSTALL/bin:$PATH"
          deno --version
      - run: /root/.deno/bin/deno run -A --unstable https://deno.land/x/pact/src/downloadFfi.ts --run
      - run: curl -fsSL https://raw.githubusercontent.com/pact-foundation/pact-plugins/main/scripts/install-plugin-cli.sh | bash
      - run: /root/bin/pact-plugin-cli -y install https://github.com/pactflow/pact-protobuf-plugin/releases/latest
      #   if: runner.os == 'Linux'
      # - run: /Users/runner/bin/pact-plugin-cli -y install https://github.com/pactflow/pact-protobuf-plugin/releases/latest
      #   if: runner.os == 'macOS'
      - run: /root/.bun/bin/bun install
      - run: /root/.bun/bin/bun run src/http.consumer.test.ts
      - run: /root/.bun/bin/bun run src/grpc.consumer.test.ts
